import { test } from 'node:test';
import assert from 'node:assert/strict';
import { GameEngine } from '../src/core/engine.js';

function simpleBoard() { return { width: 5, height: 1, walls: new Set(), oneway: new Map(), gates: [{ side: 'right', line: 0, color: 0 }], blocks: [{ id: 0, x: 0, y: 0, w: 1, h: 1, color: 0 }] }; }

test('start前の移動は状態を変えない', () => { const e = new GameEngine(simpleBoard()); const r = e.tryMove(0, 'right', 1000); assert.equal(r.moved, false); assert.equal(e.status, 'ready'); assert.equal(e.swipeCount, 0); assert.equal(e.distanceCells, 0); });
test('startは二重開始で時刻を変えない', () => { const e = new GameEngine(simpleBoard()); assert.equal(e.start(1000), true); assert.equal(e.start(2000), false); assert.equal(e.startedAt, 1000); });
test('成功スライドで操作数と移動距離が分かれて増え、退場も1操作', () => { const e = new GameEngine(simpleBoard()); e.start(10); const r = e.tryMove(0, 'right', 110); assert.equal(r.moved, true); assert.equal(r.exit, true); assert.equal(r.steps, 5); assert.equal(e.swipeCount, 1); assert.equal(e.distanceCells, 5); assert.equal(e.moveCount, 5); assert.equal(e.status, 'cleared'); });
test('不正移動では両方増えない', () => { const e = new GameEngine(simpleBoard()); e.start(0); const r = e.tryMove(0, 'left', 10); assert.equal(r.moved, false); assert.equal(e.swipeCount, 0); assert.equal(e.distanceCells, 0); });
test('クリア時刻が渡した単調時刻で固定される', () => { const e = new GameEngine(simpleBoard()); e.start(100); e.tryMove(0, 'right', 250); assert.equal(e.clearedAt, 250); assert.equal(e.elapsedMs(999), 150); });
test('elapsedMsがready、playing、clearedで正しい', () => { const e = new GameEngine(simpleBoard()); assert.equal(e.elapsedMs(100), 0); e.start(100); assert.equal(e.elapsedMs(175), 75); e.tryMove(0, 'right', 220); assert.equal(e.elapsedMs(999), 120); });
test('複数ブロック: 全部退場でクリア', () => { const e = new GameEngine({ width: 4, height: 2, walls: new Set(), oneway: new Map(), gates: [{ side: 'right', line: 0, color: 0 }, { side: 'top', line: 2, color: 1 }], blocks: [{ id: 0, x: 1, y: 0, w: 1, h: 1, color: 0 }, { id: 1, x: 2, y: 0, w: 1, h: 1, color: 1 }] }); e.start(0); assert.equal(e.tryMove(0, 'right', 1).moved, false); let r = e.tryMove(1, 'up', 2); assert.equal(r.exit, true); assert.equal(e.isCleared(), false); r = e.tryMove(0, 'right', 10); assert.equal(r.exit, true); assert.equal(r.cleared, true); });
test('resetで状態、履歴、undoCountが戻る', () => { const e = new GameEngine(simpleBoard()); e.start(0); e.tryMove(0, 'right', 1); e.reset(); assert.equal(e.status, 'ready'); assert.equal(e.swipeCount, 0); assert.equal(e.distanceCells, 0); assert.equal(e.undoCount, 0); assert.equal(e.history.length, 0); assert.deepEqual(e.positions, [{ x: 0, y: 0 }]); });
test('undoで位置、操作数、距離が戻りタイマーは戻らない', () => { const e = new GameEngine({ width: 3, height: 1, walls: new Set(), oneway: new Map(), gates: [], blocks: [{ id: 0, x: 0, y: 0, w: 1, h: 1, color: 0 }] }); e.start(100); e.tryMove(0, 'right', 150); assert.equal(e.swipeCount, 1); assert.equal(e.undo().undone, true); assert.deepEqual(e.positions, [{ x: 0, y: 0 }]); assert.equal(e.swipeCount, 0); assert.equal(e.distanceCells, 0); assert.equal(e.undoCount, 1); assert.equal(e.elapsedMs(200), 100); });
test('履歴なしとクリア後のundoは失敗する', () => { const e = new GameEngine(simpleBoard()); e.start(0); assert.equal(e.undo().undone, false); e.tryMove(0, 'right', 10); assert.equal(e.undo().undone, false); });
test('blockAt は退場後 -1 を返す', () => { const e = new GameEngine(simpleBoard()); e.start(0); assert.equal(e.blockAt(0, 0), 0); e.tryMove(0, 'right', 10); assert.equal(e.blockAt(0, 0), -1); });
